### ISSUE TITLE
Hibernate: Incorrect types mapped

### ISSUE THREAD

**Issue by tme5092** [Lucasvo1/FHVGIS#10]
When calling:  
http://localhost:8080/fhvgis/app/conv/track/003ce1ca-9808-4c08-a304-afd9604fe223

Message:  
_Unzulässiger Wert für den Typ Long: 2015-12-15 22:08:49_

Obviously, that's not a long.

Has anybody checked an tested loading/saving of all entities?

Also:  
What's the difference with between `at.fhv.itm14.fhvgis.persistence.dao.RawMotionValuesDao`
and
`at.fhv.itm14.fhvgis.persistence.dao.raw.RawMotionValueDao`

**Comment by Steve2301** [comment]
Problems solved. Change type of timestamp column in database to bigint
