### ISSUE TITLE
Hibernate: Constraint violation

### ISSUE THREAD

**Issue by tme5092** [Lucasvo1/FHVGIS#13]
When updating a waypoint, the following exception occurs:  

FEHLER: Einfügen oder Aktualisieren in Tabelle „waypoint_motion_values“ verletzt Fremdschlüssel-Constraint „fk_waypoint_motion_values_motion_id“
  Detail: Schlüssel (motion_values_id)=(ea96c5b0-eb26-4415-a789-84b6ae25c7a7) ist nicht in Tabelle „motion_values“ vorhanden.

Interesting:  
The id of the waypoint is: ea96c5b0-eb26-4415-a789-84b6ae25c7a7 - which is the value named in the violation.  
Looks like the id mapping is wrong.

**Comment by Steve2301** [comment]
fixed
