### ISSUE TITLE
Hibernate: NoClassDefFoundError

### ISSUE THREAD

**Issue by tme5092** [Lucasvo1/FHVGIS#9]
Rest exception: <html><head><title>Apache Tomcat/7.0.52 (Ubuntu) - Error report</title><style></style> </head><body><h1>HTTP Status 500 - java.lang.NoClassDefFoundError: Could not initialize class at.fhv.itm14.fhvgis.persistence.utils.HibernateUtil</h1><HR size="1" noshade="noshade"><p><b>type</b> Exception report</p><p><b>message</b> <u>java.lang.NoClassDefFoundError: Could not initialize class at.fhv.itm14.fhvgis.persistence.utils.HibernateUtil</u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b> <pre>javax.servlet.ServletException: java.lang.NoClassDefFoundError: Could not initialize class at.fhv.itm14.fhvgis.persistence.utils.HibernateUtil
    com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:420)
    com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
    com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:439)
    org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:178)
    </pre></p><p><b>root cause</b> <pre>java.lang.NoClassDefFoundError: Could not initialize class at.fhv.itm14.fhvgis.persistence.utils.HibernateUtil
    at.fhv.itm14.fhvgis.persistence.dao.DeviceDao.findDeviceByToken(DeviceDao.java:69)
    at.fhv.itm14.fhvgis.persistence.DatabaseController.findDeviceByToken(DatabaseController.java:353)
    at.fhv.itm14.fhvgis.webservice.app.services.UserService.getDevice(UserService.java:140)
    at.fhv.itm14.fhvgis.webservice.app.services.UserService.valid(UserService.java:130)
    at.fhv.itm14.fhvgis.webservice.app.controller.AppController.getVersions(AppController.java:31)
    sun.reflect.GeneratedMethodAccessor496.invoke(Unknown Source)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:497)
    com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
    com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
    com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
    com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
    com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
    com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
    com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
    com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
    com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
    com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
    com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
    com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
    com.sun.

**Comment by Steve2301** [comment]
Problem solved. Error in at.fhv.itm14.fhvgis.domain.Track. Set annotation @Transient to method  isAnalysable()
